apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
  CATALOGUE_HOST : "catalogue"
  CATALOGUE_PORT : "8080"
  USER_HOST      : "user"
  USER_PORT      : "8080"
  CART_HOST      : "cart"
  CART_PORT      : "8080"
  SHIPPING_HOST  : "shipping"
  SHIPPING_PORT  : "8080"
  PAYMENT_HOST   : "payment"
  PAYMENT_PORT   : "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
data:
  MONGO       : "true"
  MONGO_URL   : "mongodb://mongodb-dev.robobal.store.online:27017/catalogue"
  DB_TYPE     : "mongo"
  APP_GIT_URL : "https://github.com/roboshop-devops-project-v3/catalogue"
  DB_HOST     : "mongodb-dev.robobal.store.online"
  SCHEMA_FILE : "db/master-data.js"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
data:
  REDIS_HOST     : "redis-dev.robobal.store.online"
  CATALOGUE_HOST : "catalogue"
  CATALOGUE_PORT : "8080"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
data:
  MONGO     : "true"
  REDIS_URL : "redis://redis-dev.robobal.store.online:6379"
  MONGO_URL : "mongodb://mongodb-dev.robobal.store.online:27017/users"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
data:
  CART_ENDPOINT : "cart:8080"
  DB_HOST       : "mysql-dev.robobal.store.online"
  DB_USER       : "root"
  DB_PASS       : "RoboShop@1"
  DB_TYPE       : "mysql"
  APP_GIT_URL   : "https://github.com/roboshop-devops-project-v3/shipping"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment
data:
  CART_HOST : "cart"
  CART_PORT : "8080"
  USER_HOST : "user"
  USER_PORT : "8080"
  AMQP_HOST : "rabbitmq-dev.robobal.store.online"
  AMQP_USER : "roboshop"
  AMQP_PASS : "roboshop123"

